Added min and max value functions to extract the maximum or minimum v…
cityheroes/formula-values pull request #1
Opened 2018-10-08 13:47 UTC by santiagoeid93

Created min and max functions to extract the minimum/maximum value within arrays. Functions filter out anything that isn't a number from arrays for improved functionality.

2018-10-08 14:25 UTC, maurotrigo commented on src/Helpers.js
> +		if (array != 0) {
To check if a variable is an array, please use ```Array.isArray() ```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

So, the condition should be:

```if (Array.isArray(array) && array.length > 0)```

2018-10-08 14:25 UTC, maurotrigo commented on src/Helpers.js
> +	function max(array) {
The argument name ```array``` could lead to confusion and errors, since it's a generic term in most programming languages (and a reserved word in some of them). Also, at the beginning of the function, it's not clear that the variable is in fact an array. Please use another variable name, like *value*.

2018-10-08 14:25 UTC, maurotrigo commented on src/Helpers.js
> +			return maxFilteredArray;
In this case, it's not necessary to assign the result to a variable, since it's not being evaluated and the impact on legibility is small. It's better to return the result of _.max directly.

2018-10-08 15:12 UTC, santiagoeid93 commented on src/Helpers.js
> +	function max(array) {
array has been changed to value as specified.

2018-10-08 15:12 UTC, santiagoeid93 commented on src/Helpers.js
> +		if (array != 0) {
Conditional statement modified. Thanks!

2018-10-08 15:12 UTC, santiagoeid93 commented on src/Helpers.js
> +			return maxFilteredArray;
Proposed change done!

2018-10-08 15:17 UTC, maurotrigo approved these changes

2018-10-10 15:54 UTC, maurotrigo approved these changes

2018-10-11 14:06 UTC, jlarteaga requested changes
I suggest to include tests for numbers, null and undefined values, and strings, so the behaviour of both functions is completely detailed.

2018-10-15 13:00 UTC, santiagoeid93 commented
@jlarteaga I added the specified tests and changed the return values from boolean to null as adviced. The changes are included in the third commit.

2018-10-15 13:56 UTC, jlarteaga approved these changes

2018-10-15 14:02 UTC, merged